#!/bin/bash

delimiter='---'
buffer=""
tail -f output.md | while IFS= read -r line; do
    if [[ $line == "$delimiter" ]]; then
        if [[ -n $buffer ]]; then
            echo -e "$buffer" | mdcat
            buffer=""
        fi
        echo $delimiter | mdcat
    else
        buffer+=$line$'\n'
    fi
done
